export const MXP = {
  FIRST_BYTE: 4,
  P50: 3,
  P90: 1,
  TIMER_MILESTONES: 2,
  STOP_ON_TIME: 2,
  EARLY_BLOCKER: 2,
  EARLY_BLOCKER_WINDOW_SEC: 300,
  PARENT_GOAL_DAILY_CAP: 10,
  SHIELDS_PER_DAY_CAP: 1,
  TIMER_MILESTONES_AT: [180, 600, 900] as const,
};

export const FLAGS = {
  REFLECTION_GATE_SECONDS: 10,
  ENABLE_TIER1_GAMIFICATION: true,
};